server:
  port: 80
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false # 现在关闭系统的安全配置
info:
  app.name: xxl-microboot              # 应用名称
  company.name: https://luckilyxxl.xyz   # 开发公司
  pom.artifactId: $project.artifactId$   # 项目名称，通过pom获得
  pom.version: $project.version$        # 项目版本，通过pom获得