server:
  port: 80
spring:
  mail:
    host: smtp.qq.com                       # 邮箱服务器
    username: 508686616@qq.com              # 用户名
    password: clxcgqofubazbgcj              # 授权码
    properties:
      mail.smtp.auth: true                  # stmp授权开启
      mail.smtp.starttls.enable: true       # 启动tls服务
      mail.smtp.starttls.required: true     # 启动tls支持