server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/xxl_springboot_action?serverTimezone=UTC&useSSL=false           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: xxl666                                # 数据库连接密码
#    dbcp2: # 进行数据库连接池的配置
#      min-idle: 1                                   # 数据库连接池的最小维持连接数
#      initial-size: 1                               # 初始化提供的连接数
#      max-total: 1                                  # 最大的连接数
#      max-wait-millis: 3000                         # 等待连接获取的最大超时时间
  jpa:
    show-sql: true # 控制台显示SQL
    hibernate:
      ddl-auto: update # 新或者创建数据表结构